import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { items, clientName, clientEmail, invoiceNumber } = await req.json();
    if (!items || items.length === 0) return NextResponse.json({ error: 'No items' }, { status: 400 });

    const total = items.reduce((s: number, i: any) => s + i.quantity * i.rate, 0);
    const vat = Math.round(total * 20) / 100;
    const grand = total + vat;

    const html = `<!DOCTYPE html><html><head><style>
body{font-family:Arial,sans-serif;padding:40px;color:#1e293b}
.header{display:flex;justify-content:space-between;margin-bottom:40px}
.logo{font-size:24px;font-weight:900}.logo span{color:#6366f1}
.meta{text-align:right;font-size:12px;color:#64748b}
table{width:100%;border-collapse:collapse;margin-bottom:30px}
th{background:#f1f5f9;padding:12px;text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:1px;color:#64748b}
td{padding:12px;border-bottom:1px solid #f1f5f9;font-size:14px}
.totals{text-align:right}.totals .grand{font-size:24px;font-weight:900;color:#6366f1}
.footer{margin-top:60px;font-size:11px;color:#94a3b8;text-align:center}
</style></head><body>
<div class="header"><div class="logo">Invoice<span>AI</span></div>
<div class="meta"><p><strong>${invoiceNumber || 'INV-' + Date.now().toString().slice(-6)}</strong></p>
<p>Date: ${new Date().toLocaleDateString('en-GB')}</p>
<p>Due: ${new Date(Date.now()+30*86400000).toLocaleDateString('en-GB')}</p></div></div>
<h3 style="font-size:12px;text-transform:uppercase;letter-spacing:2px;color:#94a3b8">Bill To</h3>
<p><strong>${clientName||'Client'}</strong></p><p>${clientEmail||''}</p>
<table><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>
${items.map((i:any)=>`<tr><td>${i.description}</td><td>${i.quantity}</td><td>£${i.rate.toFixed(2)}</td><td>£${(i.quantity*i.rate).toFixed(2)}</td></tr>`).join('')}
</tbody></table>
<div class="totals"><p>Subtotal: <strong>£${total.toFixed(2)}</strong></p>
<p>VAT (20%): <strong>£${vat.toFixed(2)}</strong></p>
<p class="grand">Total: £${grand.toFixed(2)}</p></div>
<div class="footer"><p>Generated by InvoiceAI · AI-Powered Invoicing for UK Freelancers</p></div>
</body></html>`;

    return new NextResponse(html, { headers: { 'Content-Type': 'text/html' } });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
